### ISSUE TITLE
Periodically crashes on Linux Mint

### ISSUE THREAD

**Issue by logbasetwo** [zDEFz/c2-patch#3]
The patch appears to work very well on Linux, very pleased with how it has turned out. Admittedly, I am running Linux Mint 18.2 (Based on Ubuntu 16.04) on a desktop I haven't used for a while and need to upgrade to a currently supported distro. I will try again with a later version when I upgrade everything fully.

I have succesfully played for close to an hour with only a few crashes. Here is an example of the log file when it crashes:

sh 'Linux-32-Start cultris2.sh'
Cultris II 1.4c Community Patch 20/12/2021, Network 29
Fastl33t 120 3.5
LWJGL 2.8.5
OpenGL 3.0
BASS 2040800
Flux capacitor engaged! DeLorean went 2.143 forwards.
Update check: false false
Connection with 212.35.11.31
Closing connection with 212.35.11.31
Connection with 212.35.11.31
RoomStateChanged/GAME_OVER: Cannot locate player #243450
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "<local1>" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at UE-BASS.FPSfoundHere(Unknown Source)
	at ib-Remaining-sht-in-UpdateManager.break(Unknown Source)
	at net.gewaltig.cultris.Cultris.short(Unknown Source)
	at net.gewaltig.cultris.Cultris.main(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "<local1>" is null
	at OC-game-parameters.catch(Unknown Source)
	at Ug-BASS-error.break(Unknown Source)
	at Ug-BASS-error.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
----------------------- Remaining sh.t in UpdateManager
UE-BASS@7e0b85f9
qC@30ee2816
Mg@1f12e153
Mg@389562d6
oF@3a60c416
Mg@2160e52a
Mg@6ad11a56
Mg@18fdb6cf
Closing connection with 212.35.11.31
Flux capacitor engaged! DeLorean went 30.698000000000093 forwards.

Could this just be a Gewaltig server crash?

**Comment by zDEFz** [comment]
Hi. I also use Linux Mint, but the Linux Mint Debian edition *bullseye*.
It works very well. This error is related to UE - which is the audio engine. You can try to disable BASS which disables it altogether. Crashes should be happening when you do nothing at any given point. i.e initial game screen.

**Comment by logbasetwo** [comment]
I used to use LMDE until I had some dual monitor issues with my graphics card many years ago. I may end switching back if upgrading multiple versions gives me problems (and trying to move away from Ubuntu). Does the menu option "skip audio" disable BASS? Or is it specific to the OS? I'm using pulse audio.

**Comment by zDEFz** [comment]
> I used to use LMDE until I had some dual monitor issues with my graphics card many years ago. I may end switching back if upgrading multiple versions gives me problems (and trying to move away from Ubuntu). Does the menu option "skip audio" disable BASS? Or is it specific to the OS? I'm using pulse audio.

It does indeed. By the way: Performance on i3wm is the best for Cultris II. You really should try it. It's amazing. it's much better than on Windows. However, you require to use xrandr to setup your display.

**Comment by logbasetwo** [comment]
I'm not opposed to using xrandr, as long as it actually works. Some distros have lacked hardware support in the past. I keep coming back to Mint because of issues like that. I really liked Manjaro, but as of 5-6 years ago I couldn't get multiple monitors running with the hardware I had.

Do you run c2 with sound? Have you experienced any crashes like this in i3wmm?

**Comment by zDEFz** [comment]
> Do you run c2 with sound? Have you experienced any crashes like this in i3wmm?

Without sound. I didn't experience any crashes. Hardware is a Lenovo T490. My gaming Rig is much more powerful - but the gain is little for c2.
But my actual settings on i3wm are around 400 or 1800fps, skip audio, no animations, no blur.
This only works properly if the server is fine :) But it is so amazing to play on - I can play 20-30 bpm faster.

**Comment by logbasetwo** [comment]
I usually play c2 on a T460p and it runs great through Windows. Now that I have a job which gives me their own hardware I am tempted to switch fully over to Linux. There isn't much that's holding me back anymore. I'm happy that c2 seems to be one less reason :)

I personally prefer hearing the sounds as I don't have to focus as intently on the pending lines and I feel like I react faster.

**Comment by zDEFz** [comment]
> I usually play c2 on a T460p and it runs great through Windows. Now that I have a job which gives me their own hardware I am tempted to switch fully over to Linux. 

You will definitely gain Performance. But really - i3wm is the exception here. I play some very cpu intensive games, for instance Noita. And without i3wm I had like 30 to 45 fps. With i3wm I mostly have 60fps. And that thing runs through steamproton (wine)
On Windows? Far worse. Unplayable.

**Note** You definitely should use a new kernel! I think 5.17 is the most recent official signed kernel. 5.16 is ok, too. But 5.12 *default* is not good enough

The only thing bad about i3wm is the learning curve. I basically create new terminal windows to adjust the C2 window size. Then I have a shortcut to hide some Windows in i3wm. Was called something like send to scratchpad.
